<?php

/**
 * This is the model base class for the table "setup_mst_lookups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SetupMstLookups".
 *
 * Columns in table "setup_mst_lookups" available as properties of the model,
 * followed by relations of table "setup_mst_lookups" available as properties of the model.
 *
 * @property string $n_coy_id
 * @property string $v_lookup_code
 * @property string $v_lookup_name
 * @property string $v_lookup_desc
 * @property string $v_flag
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 *
 * @property SetupDtlLookups[] $setupDtlLookups
 * @property SetupMstOrganizations $nCoy
 */
abstract class BaseSetupMstLookups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setup_mst_lookups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SetupMstLookups|SetupMstLookups', $n);
	}

	public static function representingColumn() {
		return 'v_lookup_name';
	}

	public function rules() {
		return array(
			array('n_coy_id, v_lookup_code, v_lookup_name, v_created_by, d_created_date', 'required'),
			array('n_coy_id', 'length', 'max'=>22),
			array('v_lookup_code', 'length', 'max'=>60),
			array('v_lookup_name, v_lookup_desc', 'length', 'max'=>150),
			array('v_flag', 'length', 'max'=>1),
			array('v_created_by, v_updated_by', 'length', 'max'=>30),
			array('d_updated_date', 'safe'),
			array('v_lookup_desc, v_flag, v_updated_by, d_updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('n_coy_id, v_lookup_code, v_lookup_name, v_lookup_desc, v_flag, v_created_by, d_created_date, v_updated_by, d_updated_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'setupDtlLookups' => array(self::HAS_MANY, 'SetupDtlLookups', 'v_lookup_code'),
			'nCoy' => array(self::BELONGS_TO, 'SetupMstOrganizations', 'n_coy_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'n_coy_id' => Yii::t('app','Coy Id'),
			'v_lookup_code' => Yii::t('app', 'Lookup Code'),
			'v_lookup_name' => Yii::t('app', 'Lookup Name'),
			'v_lookup_desc' => Yii::t('app', 'Lookup Desc'),
			'v_flag' => Yii::t('app', 'Flag'),
			'v_created_by' => Yii::t('app', 'Created By'),
			'd_created_date' => Yii::t('app', 'Created Date'),
			'v_updated_by' => Yii::t('app', 'Updated By'),
			'd_updated_date' => Yii::t('app', 'Updated Date'),
			'setupDtlLookups' => Yii::t('app','SetupDtlLookups'),
			'nCoy' => Yii::t('app','NCoy'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('n_coy_id', $this->n_coy_id);
		$criteria->compare('v_lookup_code', $this->v_lookup_code, true);
		$criteria->compare('v_lookup_name', $this->v_lookup_name, true);
		$criteria->compare('v_lookup_desc', $this->v_lookup_desc, true);
		$criteria->compare('v_flag', $this->v_flag, true);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}