<?php

/**
 * This is the model base class for the table "setup_dtl_lookups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SetupDtlLookups".
 *
 * Columns in table "setup_dtl_lookups" available as properties of the model,
 * followed by relations of table "setup_dtl_lookups" available as properties of the model.
 *
 * @property string $n_coy_id
 * @property string $n_org_id
 * @property string $v_lookup_code
 * @property string $v_lookup_dtl_code
 * @property string $v_lookup_dtl_name
 * @property string $v_lookup_dtl_desc
 * @property string $v_flex
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 * @property string $v_sub_kelompok
 * @property string $v_kelompok
 * @property string $v_laporan
 * @property string $v_dr_cr
 * @property string $v_variable_1
 * @property string $v_variable_2
 * @property string $v_variable_3
 * @property string $v_variable_4
 * @property string $v_variable_5
 * @property string $v_variable_6
 *
 * @property SetupMstOrganizations $nOrg
 * @property SetupMstLookups $vLookupCode
 */
abstract class BaseSetupDtlLookups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setup_dtl_lookups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SetupDtlLookups|SetupDtlLookups', $n);
	}

	
	public static function representingColumn() {
		return array('v_lookup_code','v_lookup_dtl_code');
	}

	public function rules() {
		return array(
			array('n_coy_id, n_org_id, v_lookup_code, v_lookup_dtl_code, v_lookup_dtl_name, v_lookup_dtl_desc, v_created_by, d_created_date', 'required'),
			array('n_coy_id, n_org_id', 'length', 'max'=>22),
			array('v_lookup_code, v_lookup_dtl_code, v_sub_kelompok, v_kelompok, v_laporan', 'length', 'max'=>60),
			array('v_lookup_dtl_name', 'length', 'max'=>150),
			array('v_lookup_dtl_desc', 'length', 'max'=>500),
			array('v_flex', 'length', 'max'=>1),
			array('v_created_by, v_updated_by', 'length', 'max'=>30),
			array('v_dr_cr', 'length', 'max'=>2),
			array('v_variable_1', 'length', 'max'=>200),
			array('v_variable_2, v_variable_3, v_variable_4, v_variable_5, v_variable_6', 'length', 'max'=>15),
			array('d_updated_date', 'safe'),
			array('v_flex, v_updated_by, d_updated_date, v_sub_kelompok, v_kelompok, v_laporan, v_dr_cr, v_variable_1, v_variable_2, v_variable_3, v_variable_4, v_variable_5, v_variable_6', 'default', 'setOnEmpty' => true, 'value' => null),
			array('n_coy_id, n_org_id, v_lookup_code, v_lookup_dtl_code, v_lookup_dtl_name, v_lookup_dtl_desc, v_flex, v_created_by, d_created_date, v_updated_by, d_updated_date, v_sub_kelompok, v_kelompok, v_laporan, v_dr_cr, v_variable_1, v_variable_2, v_variable_3, v_variable_4, v_variable_5, v_variable_6', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nOrg' => array(self::BELONGS_TO, 'SetupMstOrganizations', 'n_org_id'),
			'nCoy' => array(self::BELONGS_TO, 'SetupMstOrganizations', 'n_coy_id'),
			'vLookupCode' => array(self::BELONGS_TO, 'SetupMstLookups', 'v_lookup_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'n_coy_id' => Yii::t('app', 'Coy'),
			'n_org_id' => Yii::t('app','Org Id'),
			'v_lookup_code' => Yii::t('app','Lookup Code'),
			'v_lookup_dtl_code' => Yii::t('app', 'Lookup Dtl Code'),
			'v_lookup_dtl_name' => Yii::t('app', 'Lookup Dtl Name'),
			'v_lookup_dtl_desc' => Yii::t('app', 'Lookup Dtl Desc'),
			'v_flex' => Yii::t('app', 'Flex'),
			'v_created_by' => Yii::t('app', 'Created By'),
			'd_created_date' => Yii::t('app', 'Created Date'),
			'v_updated_by' => Yii::t('app', 'Updated By'),
			'd_updated_date' => Yii::t('app', 'Updated Date'),
			'v_sub_kelompok' => Yii::t('app', 'Sub Kelompok'),
			'v_kelompok' => Yii::t('app', 'Kelompok'),
			'v_laporan' => Yii::t('app', 'Laporan'),
			'v_dr_cr' => Yii::t('app', 'Dr Cr'),
			'v_variable_1' => Yii::t('app', 'Variable 1'),
			'v_variable_2' => Yii::t('app', 'Variable 2'),
			'v_variable_3' => Yii::t('app', 'Variable 3'),
			'v_variable_4' => Yii::t('app', 'Variable 4'),
			'v_variable_5' => Yii::t('app', 'Variable 5'),
			'v_variable_6' => Yii::t('app', 'Variable 6'),
			'nOrg' => Yii::t('app','NOrg'),
			'vLookupCode' => Yii::t('app','VLookupCode'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('n_lookup_dtl_id', $this->n_lookup_dtl_id);
		$criteria->compare('n_coy_id', $this->n_coy_id, true);
		$criteria->compare('n_org_id', $this->n_org_id);
		$criteria->compare('v_lookup_code', $this->v_lookup_code);
		$criteria->compare('v_lookup_dtl_code', $this->v_lookup_dtl_code, true);
		$criteria->compare('v_lookup_dtl_name', $this->v_lookup_dtl_name, true);
		$criteria->compare('v_lookup_dtl_desc', $this->v_lookup_dtl_desc, true);
		$criteria->compare('v_flex', $this->v_flex, true);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);
		$criteria->compare('v_sub_kelompok', $this->v_sub_kelompok, true);
		$criteria->compare('v_kelompok', $this->v_kelompok, true);
		$criteria->compare('v_laporan', $this->v_laporan, true);
		$criteria->compare('v_dr_cr', $this->v_dr_cr, true);
		$criteria->compare('v_variable_1', $this->v_variable_1, true);
		$criteria->compare('v_variable_2', $this->v_variable_2, true);
		$criteria->compare('v_variable_3', $this->v_variable_3, true);
		$criteria->compare('v_variable_4', $this->v_variable_4, true);
		$criteria->compare('v_variable_5', $this->v_variable_5, true);
		$criteria->compare('v_variable_6', $this->v_variable_6, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}