<?php

/**
 * This is the model base class for the table "setup_mst_parameters".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SetupMstParameters".
 *
 * Columns in table "setup_mst_parameters" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $v_param_code
 * @property string $v_param_name
 * @property string $v_param_desc
 * @property string $v_flag
 * @property string $n_value_number
 * @property string $d_value_date
 * @property string $v_value_char
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 *
 */
abstract class BaseSetupMstParameters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setup_mst_parameters';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SetupMstParameters|SetupMstParameters', $n);
	}

	public static function representingColumn() {
		return 'v_param_name';
	}

	public function rules() {
		return array(
			array('v_param_code, v_param_name, v_flag, v_created_by, d_created_date', 'required'),
			array('v_param_code', 'length', 'max'=>60),
			array('v_param_name, v_param_desc', 'length', 'max'=>150),
			array('v_flag', 'length', 'max'=>1),
			array('n_value_number, v_created_by, v_updated_by', 'length', 'max'=>30),
			array('v_value_char', 'length', 'max'=>4000),
			array('d_value_date, d_updated_date', 'safe'),
			array('v_param_desc, n_value_number, d_value_date, v_value_char, v_updated_by, d_updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('v_param_code, v_param_name, v_param_desc, v_flag, n_value_number, d_value_date, v_value_char, v_created_by, d_created_date, v_updated_by, d_updated_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'v_param_code' => Yii::t('app', 'Param Code'),
			'v_param_name' => Yii::t('app', 'Param Name'),
			'v_param_desc' => Yii::t('app', 'Param Desc'),
			'v_flag' => Yii::t('app', 'Flag'),
			'n_value_number' => Yii::t('app', 'Value Number'),
			'd_value_date' => Yii::t('app', 'Value Date'),
			'v_value_char' => Yii::t('app', 'Value Char'),
			'v_created_by' => Yii::t('app', 'Created By'),
			'd_created_date' => Yii::t('app', 'Created Date'),
			'v_updated_by' => Yii::t('app', 'Updated By'),
			'd_updated_date' => Yii::t('app', 'Updated Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('v_param_code', $this->v_param_code, true);
		$criteria->compare('v_param_name', $this->v_param_name, true);
		$criteria->compare('v_param_desc', $this->v_param_desc, true);
		$criteria->compare('v_flag', $this->v_flag, true);
		$criteria->compare('n_value_number', $this->n_value_number, true);
		$criteria->compare('d_value_date', $this->d_value_date, true);
		$criteria->compare('v_value_char', $this->v_value_char, true);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}