<?php

/**
 * This is the model base class for the table "setup_mst_agents".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SetupMstAgents".
 *
 * Columns in table "setup_mst_agents" available as properties of the model,
 * followed by relations of table "setup_mst_agents" available as properties of the model.
 *
 * @property integer $n_agent_no
 * @property string $v_agent_code
 * @property string $v_agent_name
 * @property string $v_agent_type
 * @property string $v_status_agent
 * @property string $v_channel_no
 * @property string $v_jabatan
 * @property integer $v_reporting_to
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 * @property integer $n_coy_id
 *
 * @property PolMstPolis[] $polMstPolises
 * @property SetupMstCoys[] $setupMstCoys
 * @property SetupMstAgents $vReportingTo
 * @property SetupMstAgents[] $setupMstAgents
 */
abstract class BaseSetupMstAgents extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setup_mst_agents';
	}

	public static function label($n = 1) {
		return Yii::t('setupModule.main', 'SetupMstAgents|SetupMstAgents', $n);
	}

	public static function representingColumn() {
		return 'v_agent_name';
	}

	public function rules() {
		return array(
			array('n_agent_no, v_agent_code, v_agent_name, v_status_agent', 'required'),
			array('n_agent_no, v_reporting_to, n_coy_id', 'numerical', 'integerOnly'=>true),
			array('v_agent_code', 'length', 'max'=>20),
			array('v_agent_name', 'length', 'max'=>150),
			array('v_agent_type', 'length', 'max'=>1),
			array('v_status_agent, v_channel_no', 'length', 'max'=>10),
			array('v_jabatan, v_created_by, v_updated_by', 'length', 'max'=>30),
			array('d_created_date, d_updated_date', 'safe'),
			array('v_agent_type, v_channel_no, v_jabatan, v_reporting_to, v_created_by, d_created_date, v_updated_by, d_updated_date, n_coy_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('n_agent_no, v_agent_code, v_agent_name, v_agent_type, v_status_agent, v_channel_no, v_jabatan, v_reporting_to, v_created_by, d_created_date, v_updated_by, d_updated_date, n_coy_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'polMstPolises' => array(self::HAS_MANY, 'PolMstPolis', 'n_agent_no'),
			'setupMstCoys' => array(self::HAS_MANY, 'SetupMstCoys', 'n_existing_agent'),
			'vReportingTo' => array(self::BELONGS_TO, 'SetupMstAgents', 'v_reporting_to'),
			'setupMstAgents' => array(self::HAS_MANY, 'SetupMstAgents', 'v_reporting_to'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'n_agent_no' => Yii::t('setupModule.main', 'Agent No'),
			'v_agent_code' => Yii::t('setupModule.main', 'Agent Code'),
			'v_agent_name' => Yii::t('setupModule.main', 'Agent Name'),
			'v_agent_type' => Yii::t('setupModule.main', 'Agent Type'),
			'v_status_agent' => Yii::t('setupModule.main', 'Status Agent'),
			'v_channel_no' => Yii::t('setupModule.main', 'Channel No'),
			'v_jabatan' => Yii::t('setupModule.main', 'Jabatan'),
			'v_reporting_to' => Yii::t('setupModule.main','Reporting To'),
			'v_created_by' => Yii::t('setupModule.main', 'Created By'),
			'd_created_date' => Yii::t('setupModule.main', 'Created Date'),
			'v_updated_by' => Yii::t('setupModule.main', 'Updated By'),
			'd_updated_date' => Yii::t('setupModule.main', 'Updated Date'),
			'n_coy_id' => Yii::t('setupModule.main', 'Coy'),
			'polMstPolises' => Yii::t('setupModule.main','PolMstPolises'),
			'setupMstCoys' => Yii::t('setupModule.main','SetupMstCoys'),
			'vReportingTo' => Yii::t('setupModule.main','VReportingTo'),
			'setupMstAgents' => Yii::t('setupModule.main','SetupMstAgents'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('n_agent_no', $this->n_agent_no);
		$criteria->compare('v_agent_code', $this->v_agent_code, true);
		$criteria->compare('v_agent_name', $this->v_agent_name, true);
		$criteria->compare('v_agent_type', $this->v_agent_type, true);
		$criteria->compare('v_status_agent', $this->v_status_agent, true);
		$criteria->compare('v_channel_no', $this->v_channel_no, true);
		$criteria->compare('v_jabatan', $this->v_jabatan, true);
		$criteria->compare('v_reporting_to', $this->v_reporting_to);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);
		$criteria->compare('n_coy_id', $this->n_coy_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}