<?php

/**
 * This is the model base class for the table "upload".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Upload".
 *
 * Columns in table "upload" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $nama_file
 * @property string $upload_date
 * @property string $flag_proses
 * @property integer $uploaded_by
 *
 */
abstract class BaseUpload extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'upload';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Upload|Uploads', $n);
	}

	public static function representingColumn() {
		return 'nama_file';
	}

	public function rules() {
		return array(
			array('nama_file, upload_date, flag_proses', 'required'),
			array('uploaded_by', 'numerical', 'integerOnly'=>true),
			array('nama_file', 'length', 'max'=>50),
			array('flag_proses', 'length', 'max'=>1),
			array('uploaded_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nama_file, upload_date, flag_proses, uploaded_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nama_file' => Yii::t('app', 'Nama File'),
			'upload_date' => Yii::t('app', 'Upload Date'),
			'flag_proses' => Yii::t('app', 'Flag Proses'),
			'uploaded_by' => Yii::t('app', 'Uploaded By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nama_file', $this->nama_file, true);
		$criteria->compare('upload_date', $this->upload_date, true);
		$criteria->compare('flag_proses', $this->flag_proses, true);
		$criteria->compare('uploaded_by', $this->uploaded_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}