<?php

/**
 * This is the model base class for the table "clm_mst_claims".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClmMstClaims".
 *
 * Columns in table "clm_mst_claims" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $v_claim_no
 * @property string $v_policy_no
 * @property integer $n_line_no
 * @property string $d_claim
 * @property string $d_submitted
 * @property string $v_claim_intim
 * @property string $v_address
 * @property string $v_city
 * @property string $v_province
 * @property string $v_claim_status_note
 * @property string $v_claim_status
 * @property string $v_diagnosa_note
 * @property string $v_doc_scan
 * @property string $v_sent_by
 * @property string $v_sent_to
 * @property string $d_sent_doc
 * @property string $v_intim_email
 * @property string $v_intim_telp
 * @property string $v_bank_code
 * @property string $v_bank_cabang
 * @property string $v_rekening_no
 * @property string $v_rekening_nama
 * @property string $v_cabang_layanan
 * @property string $d_incident_date
 * @property string $v_claim_doc
 * @property string $v_verifikasi_by
 * @property string $d_verifikasi_date
 * @property string $v_upload_by
 * @property string $d_upload_date
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 *
 */
abstract class BaseClmMstClaims extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'clm_mst_claims';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClmMstClaims|ClmMstClaims', $n);
	}

	public static function representingColumn() {
		return 'v_policy_no';
	}

	public function rules() {
		return array(
			array('v_claim_no, v_policy_no, n_line_no', 'required'),
			array('n_line_no', 'numerical', 'integerOnly'=>true),
			array('v_claim_no, v_city, v_province, v_claim_status_note, v_claim_status, v_intim_email, v_intim_telp, v_bank_code, v_bank_cabang, v_rekening_no, v_cabang_layanan', 'length', 'max'=>100),
			array('v_policy_no', 'length', 'max'=>50),
			array('v_claim_intim', 'length', 'max'=>150),
			array('v_address', 'length', 'max'=>300),
			array('v_diagnosa_note, v_doc_scan, v_sent_by, v_sent_to, v_rekening_nama, v_claim_doc', 'length', 'max'=>250),
			array('v_verifikasi_by, v_upload_by, v_created_by, v_updated_by', 'length', 'max'=>30),
			array('d_verifikasi_date, d_upload_date, d_created_date, d_updated_date', 'length', 'max'=>6),
			array('d_claim, d_submitted, d_sent_doc, d_incident_date', 'safe'),
			array('d_claim, d_submitted, v_claim_intim, v_address, v_city, v_province, v_claim_status_note, v_claim_status, v_diagnosa_note, v_doc_scan, v_sent_by, v_sent_to, d_sent_doc, v_intim_email, v_intim_telp, v_bank_code, v_bank_cabang, v_rekening_no, v_rekening_nama, v_cabang_layanan, d_incident_date, v_claim_doc, v_verifikasi_by, d_verifikasi_date, v_upload_by, d_upload_date, v_created_by, d_created_date, v_updated_by, d_updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('v_claim_no, v_policy_no, n_line_no, d_claim, d_submitted, v_claim_intim, v_address, v_city, v_province, v_claim_status_note, v_claim_status, v_diagnosa_note, v_doc_scan, v_sent_by, v_sent_to, d_sent_doc, v_intim_email, v_intim_telp, v_bank_code, v_bank_cabang, v_rekening_no, v_rekening_nama, v_cabang_layanan, d_incident_date, v_claim_doc, v_verifikasi_by, d_verifikasi_date, v_upload_by, d_upload_date, v_created_by, d_created_date, v_updated_by, d_updated_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'v_claim_no' => Yii::t('app', 'V Claim No'),
			'v_policy_no' => Yii::t('app', 'V Policy No'),
			'n_line_no' => Yii::t('app', 'N Line No'),
			'd_claim' => Yii::t('app', 'D Claim'),
			'd_submitted' => Yii::t('app', 'D Submitted'),
			'v_claim_intim' => Yii::t('app', 'V Claim Intim'),
			'v_address' => Yii::t('app', 'V Address'),
			'v_city' => Yii::t('app', 'V City'),
			'v_province' => Yii::t('app', 'V Province'),
			'v_claim_status_note' => Yii::t('app', 'V Claim Status Note'),
			'v_claim_status' => Yii::t('app', 'V Claim Status'),
			'v_diagnosa_note' => Yii::t('app', 'V Diagnosa Note'),
			'v_doc_scan' => Yii::t('app', 'V Doc Scan'),
			'v_sent_by' => Yii::t('app', 'V Sent By'),
			'v_sent_to' => Yii::t('app', 'V Sent To'),
			'd_sent_doc' => Yii::t('app', 'D Sent Doc'),
			'v_intim_email' => Yii::t('app', 'V Intim Email'),
			'v_intim_telp' => Yii::t('app', 'V Intim Telp'),
			'v_bank_code' => Yii::t('app', 'V Bank Code'),
			'v_bank_cabang' => Yii::t('app', 'V Bank Cabang'),
			'v_rekening_no' => Yii::t('app', 'V Rekening No'),
			'v_rekening_nama' => Yii::t('app', 'V Rekening Nama'),
			'v_cabang_layanan' => Yii::t('app', 'V Cabang Layanan'),
			'd_incident_date' => Yii::t('app', 'D Incident Date'),
			'v_claim_doc' => Yii::t('app', 'V Claim Doc'),
			'v_verifikasi_by' => Yii::t('app', 'V Verifikasi By'),
			'd_verifikasi_date' => Yii::t('app', 'D Verifikasi Date'),
			'v_upload_by' => Yii::t('app', 'V Upload By'),
			'd_upload_date' => Yii::t('app', 'D Upload Date'),
			'v_created_by' => Yii::t('app', 'V Created By'),
			'd_created_date' => Yii::t('app', 'D Created Date'),
			'v_updated_by' => Yii::t('app', 'V Updated By'),
			'd_updated_date' => Yii::t('app', 'D Updated Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('v_claim_no', $this->v_claim_no, true);
		$criteria->compare('v_policy_no', $this->v_policy_no, true);
		$criteria->compare('n_line_no', $this->n_line_no);
		$criteria->compare('d_claim', $this->d_claim, true);
		$criteria->compare('d_submitted', $this->d_submitted, true);
		$criteria->compare('v_claim_intim', $this->v_claim_intim, true);
		$criteria->compare('v_address', $this->v_address, true);
		$criteria->compare('v_city', $this->v_city, true);
		$criteria->compare('v_province', $this->v_province, true);
		$criteria->compare('v_claim_status_note', $this->v_claim_status_note, true);
		$criteria->compare('v_claim_status', $this->v_claim_status, true);
		$criteria->compare('v_diagnosa_note', $this->v_diagnosa_note, true);
		$criteria->compare('v_doc_scan', $this->v_doc_scan, true);
		$criteria->compare('v_sent_by', $this->v_sent_by, true);
		$criteria->compare('v_sent_to', $this->v_sent_to, true);
		$criteria->compare('d_sent_doc', $this->d_sent_doc, true);
		$criteria->compare('v_intim_email', $this->v_intim_email, true);
		$criteria->compare('v_intim_telp', $this->v_intim_telp, true);
		$criteria->compare('v_bank_code', $this->v_bank_code, true);
		$criteria->compare('v_bank_cabang', $this->v_bank_cabang, true);
		$criteria->compare('v_rekening_no', $this->v_rekening_no, true);
		$criteria->compare('v_rekening_nama', $this->v_rekening_nama, true);
		$criteria->compare('v_cabang_layanan', $this->v_cabang_layanan, true);
		$criteria->compare('d_incident_date', $this->d_incident_date, true);
		$criteria->compare('v_claim_doc', $this->v_claim_doc, true);
		$criteria->compare('v_verifikasi_by', $this->v_verifikasi_by, true);
		$criteria->compare('d_verifikasi_date', $this->d_verifikasi_date, true);
		$criteria->compare('v_upload_by', $this->v_upload_by, true);
		$criteria->compare('d_upload_date', $this->d_upload_date, true);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}