<?php

/**
 * This is the model base class for the table "setup_sec_roles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SetupSecRoles".
 *
 * Columns in table "setup_sec_roles" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $n_coy_id
 * @property integer $n_org_id
 * @property string $v_role_code
 * @property string $v_role_name
 *
 */
abstract class BaseSetupSecRoles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'setup_sec_roles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SetupSecRoles|SetupSecRoles', $n);
	}

	public static function representingColumn() {
		return 'v_role_name';
	}

	public function rules() {
		return array(
			array('v_role_code, v_role_name', 'required'),
			array('n_coy_id, n_org_id', 'numerical', 'integerOnly'=>true),
			array('v_role_code', 'length', 'max'=>10),
			array('v_role_name', 'length', 'max'=>30),
			array('n_coy_id, n_org_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('n_coy_id, n_org_id, v_role_code, v_role_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'n_coy_id' => Yii::t('app', 'N Coy'),
			'n_org_id' => Yii::t('app', 'N Org'),
			'v_role_code' => Yii::t('app', 'V Role Code'),
			'v_role_name' => Yii::t('app', 'V Role Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('n_coy_id', $this->n_coy_id);
		$criteria->compare('n_org_id', $this->n_org_id);
		$criteria->compare('v_role_code', $this->v_role_code, true);
		$criteria->compare('v_role_name', $this->v_role_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}