<?php

/**
 * This is the model base class for the table "clm_dtl_claims".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClmDtlClaims".
 *
 * Columns in table "clm_dtl_claims" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $v_claim_no
 * @property integer $n_line_no
 * @property string $v_benefit
 * @property string $v_benefit_type
 * @property string $v_hospital_note
 * @property string $v_doctor_note
 * @property string $v_medicine_note
 * @property string $v_period_day_visit
 * @property string $v_medical_indicate_note
 * @property string $v_provider_non
 * @property string $v_document
 * @property integer $n_max_claim
 * @property string $n_claim_amount
 * @property string $v_telp_provider
 * @property string $v_alamat_provider
 * @property string $v_nama_provider
 * @property string $v_verifikasi_by
 * @property string $d_verifikasi_date
 * @property string $v_upload_by
 * @property string $d_upload_date
 * @property string $v_created_by
 * @property string $d_created_date
 * @property string $v_updated_by
 * @property string $d_updated_date
 *
 */
abstract class BaseClmDtlClaims extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'clm_dtl_claims';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClmDtlClaims|ClmDtlClaims', $n);
	}

	public static function representingColumn() {
		return 'v_claim_no';
	}

	public function rules() {
		return array(
			array('v_claim_no, n_line_no', 'required'),
			array('n_line_no, n_max_claim', 'numerical', 'integerOnly'=>true),
			array('v_claim_no, v_benefit_type, v_provider_non', 'length', 'max'=>100),
			array('v_benefit, v_hospital_note, v_doctor_note, v_medicine_note, v_period_day_visit, v_medical_indicate_note, v_document, v_telp_provider, v_alamat_provider, v_nama_provider', 'length', 'max'=>250),
			array('n_claim_amount, v_created_by, v_updated_by', 'length', 'max'=>30),
			array('v_verifikasi_by, v_upload_by', 'length', 'max'=>255),
			array('d_verifikasi_date, d_upload_date, d_created_date, d_updated_date', 'length', 'max'=>6),
			array('v_benefit, v_benefit_type, v_hospital_note, v_doctor_note, v_medicine_note, v_period_day_visit, v_medical_indicate_note, v_provider_non, v_document, n_max_claim, n_claim_amount, v_telp_provider, v_alamat_provider, v_nama_provider, v_verifikasi_by, d_verifikasi_date, v_upload_by, d_upload_date, v_created_by, d_created_date, v_updated_by, d_updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('v_claim_no, n_line_no, v_benefit, v_benefit_type, v_hospital_note, v_doctor_note, v_medicine_note, v_period_day_visit, v_medical_indicate_note, v_provider_non, v_document, n_max_claim, n_claim_amount, v_telp_provider, v_alamat_provider, v_nama_provider, v_verifikasi_by, d_verifikasi_date, v_upload_by, d_upload_date, v_created_by, d_created_date, v_updated_by, d_updated_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'v_claim_no' => Yii::t('app', 'V Claim No'),
			'n_line_no' => Yii::t('app', 'N Line No'),
			'v_benefit' => Yii::t('app', 'V Benefit'),
			'v_benefit_type' => Yii::t('app', 'V Benefit Type'),
			'v_hospital_note' => Yii::t('app', 'V Hospital Note'),
			'v_doctor_note' => Yii::t('app', 'V Doctor Note'),
			'v_medicine_note' => Yii::t('app', 'V Medicine Note'),
			'v_period_day_visit' => Yii::t('app', 'V Period Day Visit'),
			'v_medical_indicate_note' => Yii::t('app', 'V Medical Indicate Note'),
			'v_provider_non' => Yii::t('app', 'V Provider Non'),
			'v_document' => Yii::t('app', 'V Document'),
			'n_max_claim' => Yii::t('app', 'N Max Claim'),
			'n_claim_amount' => Yii::t('app', 'N Claim Amount'),
			'v_telp_provider' => Yii::t('app', 'V Telp Provider'),
			'v_alamat_provider' => Yii::t('app', 'V Alamat Provider'),
			'v_nama_provider' => Yii::t('app', 'V Nama Provider'),
			'v_verifikasi_by' => Yii::t('app', 'V Verifikasi By'),
			'd_verifikasi_date' => Yii::t('app', 'D Verifikasi Date'),
			'v_upload_by' => Yii::t('app', 'V Upload By'),
			'd_upload_date' => Yii::t('app', 'D Upload Date'),
			'v_created_by' => Yii::t('app', 'V Created By'),
			'd_created_date' => Yii::t('app', 'D Created Date'),
			'v_updated_by' => Yii::t('app', 'V Updated By'),
			'd_updated_date' => Yii::t('app', 'D Updated Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('v_claim_no', $this->v_claim_no, true);
		$criteria->compare('n_line_no', $this->n_line_no);
		$criteria->compare('v_benefit', $this->v_benefit, true);
		$criteria->compare('v_benefit_type', $this->v_benefit_type, true);
		$criteria->compare('v_hospital_note', $this->v_hospital_note, true);
		$criteria->compare('v_doctor_note', $this->v_doctor_note, true);
		$criteria->compare('v_medicine_note', $this->v_medicine_note, true);
		$criteria->compare('v_period_day_visit', $this->v_period_day_visit, true);
		$criteria->compare('v_medical_indicate_note', $this->v_medical_indicate_note, true);
		$criteria->compare('v_provider_non', $this->v_provider_non, true);
		$criteria->compare('v_document', $this->v_document, true);
		$criteria->compare('n_max_claim', $this->n_max_claim);
		$criteria->compare('n_claim_amount', $this->n_claim_amount, true);
		$criteria->compare('v_telp_provider', $this->v_telp_provider, true);
		$criteria->compare('v_alamat_provider', $this->v_alamat_provider, true);
		$criteria->compare('v_nama_provider', $this->v_nama_provider, true);
		$criteria->compare('v_verifikasi_by', $this->v_verifikasi_by, true);
		$criteria->compare('d_verifikasi_date', $this->d_verifikasi_date, true);
		$criteria->compare('v_upload_by', $this->v_upload_by, true);
		$criteria->compare('d_upload_date', $this->d_upload_date, true);
		$criteria->compare('v_created_by', $this->v_created_by, true);
		$criteria->compare('d_created_date', $this->d_created_date, true);
		$criteria->compare('v_updated_by', $this->v_updated_by, true);
		$criteria->compare('d_updated_date', $this->d_updated_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}